Pandas notebook

In [ ]:
import pandas as pan
import numpy as np

In [ ]:
indexes = ["mango","apple","banana","orange",]
fruites = [ 50,30,20,25]
series = pan.Series(fruites,indexes, name = "Fruites Quantity")

In [ ]:

series.iloc[[2, 3,]] 
series.loc["apple":"orange"]

In [ ]:
series.dtype

In [ ]:
series > 20

In [ ]:

series[series > 20 & (series <30)]

In [ ]:
# not operation
series[~(series >25)]

In [ ]:
# modifyign series
series["banana"] = 27
series

In [ ]:
data = {
    "fruites": indexes,
    "prices": [100, 80, 90, 60],
    "quantity": fruites,
    "sales": [np.nan,20,18,15]
}
df = pan.DataFrame(data)

In [ ]:
df.head(2)

In [ ]:

df.tail(3)

In [ ]:
df.iloc[1:3, 0:2]

In [ ]:
df.describe()

In [ ]:
df.drop(labels= "sales", axis=1)
# to remove permanentley use inplace = true
df

In [ ]:
# other codes?
df.shape
df.info()

In [ ]:
# Broadcasting
df["prices"] = df["prices"] + 20
df

In [ ]:
# renaming
df.rename(columns= {"prices": "price"}, inplace = True)

df

  fruites  price  quantity  sales
0   mango    160        50    NaN
1   apple    140        30   20.0
2  banana    150        20   18.0
3  orange    120        20   15.0

In [34]:
df["quantity"].unique

<bound method Series.unique of 0    50
1    30
2    20
3    20
Name: quantity, dtype: int64>

In [ ]:
df["quantity"] = df["quantity"].replace(25,20)

In [36]:
df["quantity"].value_counts()

quantity
20    2
50    1
30    1
Name: count, dtype: int64

In [49]:
# adding new column
df["new_prices"] = df["price"] *( 0.7 )
df["new_prices"]
# df["price"]

0    112.0
1     98.0
2    105.0
3     84.0
Name: new_prices, dtype: float64

In [54]:
# null value cheacker 
df.isnull().sum()

fruites       0
price         0
quantity      0
sales         1
new_prices    0
dtype: int64

In [ ]:
# removing null values
df.dropna()

  fruites  price  quantity  sales  new_prices
1   apple    140        30   20.0        98.0
2  banana    150        20   18.0       105.0
3  orange    120        20   15.0        84.0